/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/StepIndicator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BusTicketingForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/ConfirmationModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/FareDetailsStep`; params?: Router.UnknownInputParams; } | { pathname: `/components/FormPicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/ReceiptPrinter`; params?: Router.UnknownInputParams; } | { pathname: `/components/TripDetailsStep`; params?: Router.UnknownInputParams; } | { pathname: `/components/TripSummary`; params?: Router.UnknownInputParams; } | { pathname: `/config/bus-numbers`; params?: Router.UnknownInputParams; } | { pathname: `/config/bus-trip-constants`; params?: Router.UnknownInputParams; } | { pathname: `/config/fare-matrix`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/services/PrinterService`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/StepIndicator`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BusTicketingForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ConfirmationModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FareDetailsStep`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FormPicker`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ReceiptPrinter`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TripDetailsStep`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TripSummary`; params?: Router.UnknownOutputParams; } | { pathname: `/config/bus-numbers`; params?: Router.UnknownOutputParams; } | { pathname: `/config/bus-trip-constants`; params?: Router.UnknownOutputParams; } | { pathname: `/config/fare-matrix`; params?: Router.UnknownOutputParams; } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/services/PrinterService`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/components/StepIndicator${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/BusTicketingForm${`?${string}` | `#${string}` | ''}` | `/components/ConfirmationModal${`?${string}` | `#${string}` | ''}` | `/components/FareDetailsStep${`?${string}` | `#${string}` | ''}` | `/components/FormPicker${`?${string}` | `#${string}` | ''}` | `/components/ReceiptPrinter${`?${string}` | `#${string}` | ''}` | `/components/TripDetailsStep${`?${string}` | `#${string}` | ''}` | `/components/TripSummary${`?${string}` | `#${string}` | ''}` | `/config/bus-numbers${`?${string}` | `#${string}` | ''}` | `/config/bus-trip-constants${`?${string}` | `#${string}` | ''}` | `/config/fare-matrix${`?${string}` | `#${string}` | ''}` | `/config${`?${string}` | `#${string}` | ''}` | `/services/PrinterService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/StepIndicator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BusTicketingForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/ConfirmationModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/FareDetailsStep`; params?: Router.UnknownInputParams; } | { pathname: `/components/FormPicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/ReceiptPrinter`; params?: Router.UnknownInputParams; } | { pathname: `/components/TripDetailsStep`; params?: Router.UnknownInputParams; } | { pathname: `/components/TripSummary`; params?: Router.UnknownInputParams; } | { pathname: `/config/bus-numbers`; params?: Router.UnknownInputParams; } | { pathname: `/config/bus-trip-constants`; params?: Router.UnknownInputParams; } | { pathname: `/config/fare-matrix`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/services/PrinterService`; params?: Router.UnknownInputParams; };
    }
  }
}
